"""Keyword knowledge base for classification.

Three vocabularies drive the relevance decision:

* ``ML_TERMS``    — data-driven / AI methods.  ``(weight, tag, category)``
* ``CHEM_TERMS``  — chemistry problems and domains.  ``(weight, tag, category)``
* ``NEGATIVE_TERMS`` — signals that the paper's primary domain is NOT
  chemistry (medicine, finance, generic CS...).  ``penalty`` points.

A paper is only accepted when it matches at least one ML term AND at least one
chemistry term — that is the project's core rule: *machine learning applied to
chemistry*, not machine learning in general and not chemistry in general.

Weights: 4 = highly specific ("retrosynthesis"), 3 = strong, 2 = supportive,
1 = weak/generic.  Tags become the visible chips on paper cards; categories
group papers for browsing.
"""

from __future__ import annotations

from typing import Dict, Tuple

# ---------------------------------------------------------------------------
# Machine-learning / data-driven method terms
# ---------------------------------------------------------------------------
ML_TERMS: Dict[str, Tuple[int, str, str]] = {
    # phrase: (weight, tag, category)
    "machine learning": (3, "Machine Learning", "Machine Learning"),
    "machine-learning": (3, "Machine Learning", "Machine Learning"),
    "deep learning": (3, "Deep Learning", "Deep Learning"),
    "artificial intelligence": (2, "AI", "Machine Learning"),
    "data-driven": (2, "Data-Driven", "Machine Learning"),
    "data driven": (2, "Data-Driven", "Machine Learning"),
    "neural network": (2, "Neural Network", "Deep Learning"),
    "neural networks": (2, "Neural Network", "Deep Learning"),
    "graph neural network": (4, "Graph Neural Network", "Graph Neural Networks"),
    "graph neural networks": (4, "Graph Neural Network", "Graph Neural Networks"),
    "graph convolutional": (4, "Graph Neural Network", "Graph Neural Networks"),
    "message passing neural": (4, "Graph Neural Network", "Graph Neural Networks"),
    "convolutional neural network": (2, "CNN", "Deep Learning"),
    "recurrent neural network": (2, "RNN", "Deep Learning"),
    "transformer": (3, "Transformer", "Transformers & LLMs"),
    "attention mechanism": (2, "Transformer", "Transformers & LLMs"),
    "large language model": (4, "LLM", "Transformers & LLMs"),
    "large language models": (4, "LLM", "Transformers & LLMs"),
    "language model": (2, "LLM", "Transformers & LLMs"),
    "gpt-4": (3, "LLM", "Transformers & LLMs"),
    "chatgpt": (3, "LLM", "Transformers & LLMs"),
    "foundation model": (3, "Foundation Model", "Transformers & LLMs"),
    "generative model": (3, "Generative Model", "Generative Models"),
    "generative ai": (3, "Generative AI", "Generative Models"),
    "generative adversarial": (3, "GAN", "Generative Models"),
    "variational autoencoder": (3, "VAE", "Generative Models"),
    "autoencoder": (2, "Autoencoder", "Generative Models"),
    "diffusion model": (3, "Diffusion Model", "Generative Models"),
    "reinforcement learning": (3, "Reinforcement Learning", "Reinforcement Learning"),
    "active learning": (3, "Active Learning", "Active Learning"),
    "transfer learning": (3, "Transfer Learning", "Machine Learning"),
    "self-supervised": (3, "Self-Supervised", "Machine Learning"),
    "contrastive learning": (3, "Contrastive Learning", "Machine Learning"),
    "few-shot": (2, "Few-Shot", "Machine Learning"),
    "bayesian optimization": (4, "Bayesian Optimization", "Bayesian Optimization"),
    "bayesian optimisation": (4, "Bayesian Optimization", "Bayesian Optimization"),
    "gaussian process": (3, "Gaussian Process", "Bayesian Optimization"),
    "random forest": (3, "Random Forest", "Classical ML"),
    "gradient boosting": (3, "Gradient Boosting", "Classical ML"),
    "xgboost": (3, "XGBoost", "Classical ML"),
    "lightgbm": (3, "LightGBM", "Classical ML"),
    "support vector": (2, "SVM", "Classical ML"),
    "kernel ridge regression": (3, "Kernel Ridge", "Classical ML"),
    "k-nearest neighbor": (2, "kNN", "Classical ML"),
    "clustering": (1, "Clustering", "Classical ML"),
    "dimensionality reduction": (2, "Dimensionality Reduction", "Classical ML"),
    "genetic algorithm": (2, "Genetic Algorithm", "Optimization"),
    "evolutionary algorithm": (2, "Evolutionary Algorithm", "Optimization"),
    "surrogate model": (3, "Surrogate Model", "Machine Learning"),
    "predictive model": (2, "Predictive Model", "Machine Learning"),
    "neural network potential": (4, "ML Potential", "ML Potentials & Force Fields"),
    "machine learning potential": (4, "ML Potential", "ML Potentials & Force Fields"),
    "machine-learned potential": (4, "ML Potential", "ML Potentials & Force Fields"),
    "machine learning interatomic": (4, "ML Potential", "ML Potentials & Force Fields"),
    "interatomic potential": (3, "ML Potential", "ML Potentials & Force Fields"),
    "learned force field": (4, "ML Force Field", "ML Potentials & Force Fields"),
    "equivariant": (3, "Equivariant Model", "Graph Neural Networks"),
    "graph representation": (2, "Graph Representation", "Graph Neural Networks"),
    "chemprop": (4, "Chemprop", "Graph Neural Networks"),
    "alphafold": (2, "AlphaFold", "Deep Learning"),
    "cheminformatics": (3, "Cheminformatics", "Cheminformatics"),
    "chemoinformatics": (3, "Cheminformatics", "Cheminformatics"),
    "qsar": (4, "QSAR", "Cheminformatics"),
    "qspr": (4, "QSPR", "Cheminformatics"),
    "molecular descriptor": (3, "Descriptors", "Cheminformatics"),
    "molecular fingerprint": (3, "Fingerprints", "Cheminformatics"),
    "smiles": (3, "SMILES", "Cheminformatics"),
    "virtual screening": (3, "Virtual Screening", "Cheminformatics"),
    "high-throughput screening": (3, "High-Throughput", "High-Throughput & Autonomous"),
    "high throughput screening": (3, "High-Throughput", "High-Throughput & Autonomous"),
    "high-throughput experimentation": (4, "HTE", "High-Throughput & Autonomous"),
    "autonomous experimentation": (4, "Autonomous Lab", "High-Throughput & Autonomous"),
    "self-driving lab": (4, "Autonomous Lab", "High-Throughput & Autonomous"),
    "closed-loop optimization": (4, "Closed-Loop", "High-Throughput & Autonomous"),
    "robotic platform": (3, "Robotic Chemistry", "High-Throughput & Autonomous"),
    "uncertainty quantification": (2, "Uncertainty", "Machine Learning"),
    "explainable ai": (2, "Explainable AI", "Machine Learning"),
    "interpretable machine learning": (3, "Interpretable ML", "Machine Learning"),
    "feature importance": (1, "Feature Importance", "Machine Learning"),
    "multi-task learning": (2, "Multi-Task", "Machine Learning"),
    "federated learning": (2, "Federated Learning", "Machine Learning"),
    "in silico": (1, "In Silico", "Computational Chemistry"),
}

# ---------------------------------------------------------------------------
# Chemistry problem / domain terms
# ---------------------------------------------------------------------------
CHEM_TERMS: Dict[str, Tuple[int, str, str]] = {
    "chemistry": (2, "Chemistry", "Chemistry"),
    "chemical": (1, "Chemistry", "Chemistry"),
    "molecule": (2, "Molecules", "Molecular Science"),
    "molecular": (1, "Molecules", "Molecular Science"),
    "molecular property": (4, "Property Prediction", "Property Prediction"),
    "property prediction": (4, "Property Prediction", "Property Prediction"),
    "molecular design": (4, "Molecular Design", "Molecule Generation"),
    "molecule generation": (4, "Molecule Generation", "Molecule Generation"),
    "molecular generation": (4, "Molecule Generation", "Molecule Generation"),
    "de novo design": (4, "De Novo Design", "Molecule Generation"),
    "inverse design": (4, "Inverse Design", "Molecule Generation"),
    "reaction prediction": (4, "Reaction Prediction", "Reaction Prediction"),
    "reaction outcome": (4, "Reaction Prediction", "Reaction Prediction"),
    "reaction yield": (4, "Yield Prediction", "Reaction Prediction"),
    "yield prediction": (4, "Yield Prediction", "Reaction Prediction"),
    "retrosynthesis": (4, "Retrosynthesis", "Retrosynthesis"),
    "retrosynthetic": (4, "Retrosynthesis", "Retrosynthesis"),
    "synthesis planning": (4, "Synthesis Planning", "Retrosynthesis"),
    "synthesis route": (3, "Synthesis Planning", "Retrosynthesis"),
    "organic synthesis": (4, "Organic Synthesis", "Organic Chemistry"),
    "organic chemistry": (4, "Organic Chemistry", "Organic Chemistry"),
    "organic reaction": (4, "Organic Chemistry", "Organic Chemistry"),
    "total synthesis": (3, "Total Synthesis", "Organic Chemistry"),
    "catalysis": (4, "Catalysis", "Catalysis"),
    "catalyst": (4, "Catalysis", "Catalysis"),
    "catalytic": (3, "Catalysis", "Catalysis"),
    "electrocatalys": (4, "Electrocatalysis", "Catalysis"),
    "photocatalys": (4, "Photocatalysis", "Catalysis"),
    "heterogeneous cataly": (4, "Heterogeneous Catalysis", "Catalysis"),
    "homogeneous cataly": (4, "Homogeneous Catalysis", "Catalysis"),
    "ligand": (3, "Ligands", "Catalysis"),
    "transition metal": (3, "Transition Metals", "Inorganic Chemistry"),
    "organometallic": (4, "Organometallic", "Inorganic Chemistry"),
    "inorganic": (2, "Inorganic Chemistry", "Inorganic Chemistry"),
    "coordination complex": (3, "Coordination Chemistry", "Inorganic Chemistry"),
    "dft": (4, "DFT", "Computational Chemistry"),
    "density functional theory": (4, "DFT", "Computational Chemistry"),
    "density functional": (3, "DFT", "Computational Chemistry"),
    "ab initio": (3, "Ab Initio", "Computational Chemistry"),
    "quantum chemistry": (4, "Quantum Chemistry", "Computational Chemistry"),
    "quantum chemical": (4, "Quantum Chemistry", "Computational Chemistry"),
    "computational chemistry": (4, "Computational Chemistry", "Computational Chemistry"),
    "electronic structure": (3, "Electronic Structure", "Computational Chemistry"),
    "potential energy surface": (4, "PES", "Computational Chemistry"),
    "molecular dynamics": (3, "Molecular Dynamics", "Computational Chemistry"),
    "force field": (3, "Force Fields", "ML Potentials & Force Fields"),
    "coupled cluster": (3, "Coupled Cluster", "Computational Chemistry"),
    "excited state": (3, "Excited States", "Computational Chemistry"),
    "reaction mechanism": (3, "Reaction Mechanisms", "Reaction Prediction"),
    "transition state": (3, "Transition States", "Computational Chemistry"),
    "activation energy": (3, "Activation Energy", "Computational Chemistry"),
    "binding energy": (2, "Binding Energy", "Computational Chemistry"),
    "adsorption": (3, "Adsorption", "Surface Chemistry"),
    "surface chemistry": (4, "Surface Chemistry", "Surface Chemistry"),
    "spectroscopy": (3, "Spectroscopy", "Spectroscopy"),
    "spectra": (2, "Spectroscopy", "Spectroscopy"),
    "spectral": (1, "Spectroscopy", "Spectroscopy"),
    "nmr": (4, "NMR", "Spectroscopy"),
    "nuclear magnetic resonance": (4, "NMR", "Spectroscopy"),
    "infrared spectro": (4, "IR Spectroscopy", "Spectroscopy"),
    "raman": (4, "Raman", "Spectroscopy"),
    "mass spectrometry": (4, "Mass Spectrometry", "Spectroscopy"),
    "x-ray diffraction": (3, "XRD", "Spectroscopy"),
    "uv-vis": (3, "UV-Vis", "Spectroscopy"),
    "electrochemistry": (4, "Electrochemistry", "Electrochemistry & Batteries"),
    "electrochemical": (3, "Electrochemistry", "Electrochemistry & Batteries"),
    "battery": (3, "Batteries", "Electrochemistry & Batteries"),
    "batteries": (3, "Batteries", "Electrochemistry & Batteries"),
    "electrolyte": (3, "Electrolytes", "Electrochemistry & Batteries"),
    "electrode": (2, "Electrodes", "Electrochemistry & Batteries"),
    "fuel cell": (3, "Fuel Cells", "Electrochemistry & Batteries"),
    "polymer": (3, "Polymers", "Polymer Chemistry"),
    "polymerization": (4, "Polymerization", "Polymer Chemistry"),
    "copolymer": (3, "Polymers", "Polymer Chemistry"),
    "macromolecul": (3, "Macromolecules", "Polymer Chemistry"),
    "materials discovery": (4, "Materials Discovery", "Materials Chemistry"),
    "materials design": (4, "Materials Design", "Materials Chemistry"),
    "materials science": (2, "Materials Science", "Materials Chemistry"),
    "crystal structure": (3, "Crystal Structures", "Materials Chemistry"),
    "crystal structure prediction": (4, "Crystal Structure Prediction", "Materials Chemistry"),
    "metal-organic framework": (4, "MOFs", "Materials Chemistry"),
    "metal organic framework": (4, "MOFs", "Materials Chemistry"),
    "zeolite": (4, "Zeolites", "Materials Chemistry"),
    "perovskite": (3, "Perovskites", "Materials Chemistry"),
    "nanoparticle": (2, "Nanoparticles", "Materials Chemistry"),
    "nanomaterial": (2, "Nanomaterials", "Materials Chemistry"),
    "band gap": (3, "Band Gap", "Materials Chemistry"),
    "thermal conductivity": (2, "Thermal Properties", "Materials Chemistry"),
    "alloy": (2, "Alloys", "Materials Chemistry"),
    "solubility": (3, "Solubility", "Property Prediction"),
    "melting point": (3, "Melting Point", "Property Prediction"),
    "boiling point": (3, "Boiling Point", "Property Prediction"),
    "logp": (3, "LogP", "Property Prediction"),
    "pka": (3, "pKa", "Property Prediction"),
    "dipole moment": (3, "Dipole Moment", "Property Prediction"),
    "homo-lumo": (4, "HOMO-LUMO", "Property Prediction"),
    "atomization energy": (4, "Atomization Energy", "Property Prediction"),
    "formation energy": (3, "Formation Energy", "Property Prediction"),
    "toxicity prediction": (3, "Toxicity", "Property Prediction"),
    "admet": (3, "ADMET", "Drug Discovery Chemistry"),
    "drug discovery": (3, "Drug Discovery", "Drug Discovery Chemistry"),
    "medicinal chemistry": (4, "Medicinal Chemistry", "Drug Discovery Chemistry"),
    "lead optimization": (3, "Lead Optimization", "Drug Discovery Chemistry"),
    "structure-activity relationship": (4, "SAR", "Drug Discovery Chemistry"),
    "docking": (3, "Docking", "Drug Discovery Chemistry"),
    "protein-ligand": (3, "Protein-Ligand", "Drug Discovery Chemistry"),
    "co2 reduction": (4, "CO2 Reduction", "Catalysis"),
    "carbon capture": (3, "Carbon Capture", "Environmental Chemistry"),
    "water splitting": (4, "Water Splitting", "Catalysis"),
    "hydrogen evolution": (4, "Hydrogen Evolution", "Catalysis"),
    "oxygen evolution": (4, "Oxygen Evolution", "Catalysis"),
    "ammonia synthesis": (4, "Ammonia Synthesis", "Catalysis"),
    "green chemistry": (3, "Green Chemistry", "Environmental Chemistry"),
    "analytical chemistry": (4, "Analytical Chemistry", "Analytical Chemistry"),
    "chromatograph": (3, "Chromatography", "Analytical Chemistry"),
    "physical chemistry": (3, "Physical Chemistry", "Physical Chemistry"),
    "thermodynamic": (2, "Thermodynamics", "Physical Chemistry"),
    "kinetic": (2, "Kinetics", "Physical Chemistry"),
    "solvent": (2, "Solvents", "Physical Chemistry"),
    "ionic liquid": (3, "Ionic Liquids", "Physical Chemistry"),
    "photochemistry": (4, "Photochemistry", "Physical Chemistry"),
    "supramolecular": (4, "Supramolecular", "Molecular Science"),
    "chemical space": (4, "Chemical Space", "Cheminformatics"),
    "chemical reaction": (3, "Reactions", "Reaction Prediction"),
    "reactivity": (3, "Reactivity", "Reaction Prediction"),
    "regioselectivity": (4, "Regioselectivity", "Organic Chemistry"),
    "enantioselectivity": (4, "Enantioselectivity", "Organic Chemistry"),
    "stereoselectivity": (4, "Stereoselectivity", "Organic Chemistry"),
    "asymmetric synthesis": (4, "Asymmetric Synthesis", "Organic Chemistry"),
    "cross-coupling": (4, "Cross-Coupling", "Organic Chemistry"),
    "c-h activation": (4, "C-H Activation", "Organic Chemistry"),
    "natural product": (3, "Natural Products", "Organic Chemistry"),
}

# ---------------------------------------------------------------------------
# Negative signals — the paper's primary field is probably NOT chemistry
# ---------------------------------------------------------------------------
NEGATIVE_TERMS: Dict[str, int] = {
    # medicine / clinical
    "clinical trial": 12,
    "clinical decision": 12,
    "patients": 8,
    "patient outcomes": 12,
    "electronic health record": 15,
    "medical imaging": 12,
    "radiology": 12,
    "radiograph": 12,
    "mri scan": 10,
    "ct scan": 10,
    "histopathology": 10,
    "tumor segmentation": 12,
    "cancer diagnosis": 10,
    "disease diagnosis": 10,
    "epidemiolog": 10,
    "public health": 10,
    "genomics": 6,
    "transcriptomic": 8,
    "single-cell": 8,
    # finance / business
    "stock market": 15,
    "stock price": 15,
    "financial market": 15,
    "cryptocurrency": 15,
    "portfolio optimization": 12,
    "credit risk": 15,
    "fraud detection": 12,
    # generic CS / other fields
    "image classification": 8,
    "object detection": 10,
    "face recognition": 15,
    "autonomous driving": 12,
    "self-driving car": 12,
    "natural language processing": 5,
    "sentiment analysis": 12,
    "recommender system": 12,
    "speech recognition": 12,
    "traffic flow": 12,
    "wireless network": 12,
    "cybersecurity": 12,
    "intrusion detection": 15,
    "social media": 10,
    "supply chain": 10,
    "remote sensing": 8,
    "weather forecast": 8,
    "climate model": 6,
    "seismic": 10,
    "astro": 8,
    "galaxy": 12,
    "particle physics": 10,
    "quark": 12,
    "dark matter": 12,
    "protein folding": 4,
    "protein structure prediction": 4,
}

# Journal-name fragments that indicate a chemistry venue (score bonus).
CHEM_VENUE_HINTS = (
    "chem", "catal", "molecul", "mater", "polym", "electrochem",
    "spectro", "synth", "organomet", "faraday", "angewandte",
    "tetrahedron", "cheminformatics", "reaction", "crystal",
)
